# Generated by Django 5.1.4 on 2025-01-16 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0006_alter_reviews_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('checked', models.CharField(choices=[('✅', '✅'), ('❌', '❌')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books')),
            ],
        ),
    ]
