# Generated by Django 5.1.4 on 2025-01-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_alter_reviews_options'),
        ('my_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='task',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_address',
            field=models.CharField(max_length=150, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='promo_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.PositiveIntegerField(max_length=100, null=True, verbose_name='Кольичество'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='checked',
            field=models.CharField(choices=[('Курьер', 'Курьер'), ('Самовывоз', 'Самовывоз')], max_length=10, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='choice_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books', verbose_name='Название и цена книги'),
        ),
    ]
