# Generated by Django 5.1.4 on 2025-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_orders', '0002_remove_ordermodel_task_ordermodel_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя и Фамилия'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phon',
            field=models.TextField(max_length=16, null=True, verbose_name='Номер телефона'),
        ),
    ]
