# Generated by Django 5.1.4 on 2025-01-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_orders', '0003_ordermodel_name_ordermodel_phon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phon',
            field=models.CharField(max_length=16, null=True, verbose_name='Номер телефона'),
        ),
    ]
