# Generated by Django 5.1.4 on 2025-01-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_orders', '0004_alter_ordermodel_phon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Кольичество'),
        ),
    ]
